# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba6465030e42f2bd904794694eee780adc9fe4ecb58f98524c848de7dc7fc4fc4f47a73ccf2b3d8ad41349fe68b1e220474b3e057ebc77daf84e7414718ca634

test:
  secret_key_base: f1e582d1060212bf0803952ee6bbf7f6d175fea54b5f4590a8fc766ef4a2c3c1ecd097df0ea5b06c6ddb4057a4e5e4bb474b4dd608151e0e30bbd3de95a69264

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
